Repository ASAP-as-soon-as-possible/ASAP_Server, pull requests merged in 2024-08, with the labels that each got.

#292 #291 [feat] ContinuousMeetingTimeStrategy 구현체 코드 구현
  src/main/java/com/asap/server/persistence/domain/enums/TimeSlot.java
  src/main/java/com/asap/server/service/meeting/recommend/strategy/ContinuousMeetingTimeStrategy.java
  src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/ContinuousMeetingTimeStrategyImpl.java
  src/test/java/com/asap/server/common/generator/TimeBlockDtoGenerator.java
  src/test/java/com/asap/server/service/meeting/recommend/strategy/impl/ContinuousMeetingTimeStrategyImplTest.java
Labels: Highest

#294 #293 [feat] BestMeetingTimeStrategy 구현체 로직 개발
  src/main/java/com/asap/server/service/meeting/recommend/MeetingTimeRecommendService.java
  src/main/java/com/asap/server/service/meeting/recommend/strategy/BestMeetingTimeStrategy.java
  src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/BestMeetingTimeStrategyImpl.java
  src/test/java/com/asap/server/service/meeting/recommend/strategy/impl/BestMeetingTimeStrategyImplTest.java
Labels: Highest

#296 #295 [feat] MeetingTimeCasesStrategy 구현체 구현
  src/main/java/com/asap/server/service/meeting/recommend/MeetingTimeRecommendService.java
  src/main/java/com/asap/server/service/meeting/recommend/strategy/MeetingTimeCasesStrategy.java
  src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyImpl.java
  src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeTimeCasesStrategyImpl.java
  src/test/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyTest.java
Labels: Highest

#300 #299 [feat] 이미 추천한 회의 시간대를 이후 조합에서 추천하지 않는 로직 추가
  README.md
  src/main/java/com/asap/server/service/meeting/recommend/MeetingTimeRecommendService.java
  src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/ContinuousMeetingTimeStrategyImpl.java
  src/test/java/com/asap/server/service/meeting/recommend/MeetingTimeRecommendServiceTest.java
Labels: High

#303 #302 [fix] local date 객체를 값 비교를 하도록 수정
  src/main/java/com/asap/server/service/meeting/recommend/MeetingTimeRecommendService.java
Labels: High

#320 #316 [feat] UserMeetingSchedule 엔티티 작성 및 저장 로직 작성
  src/main/java/com/asap/server/persistence/domain/time/UserMeetingSchedule.java
  src/main/java/com/asap/server/persistence/repository/UserMeetingScheduleRepository.java
  src/main/java/com/asap/server/presentation/controller/dto/request/AvailableTimeRequestDto.java
  src/main/java/com/asap/server/presentation/controller/dto/request/UserMeetingTimeSaveRequestDto.java
  src/main/java/com/asap/server/presentation/controller/time/TimeRegisterController.java
  src/main/java/com/asap/server/service/UserService.java
  src/main/java/com/asap/server/service/time/UserMeetingScheduleService.java
  src/main/java/com/asap/server/service/time/dto/UserMeetingScheduleRegisterDto.java
  src/main/java/com/asap/server/service/time/dto/UserTimeRegisterDto.java
Labels: Medium

#324 #317 [feat] 엔티티 변경으로 인한 종합 일정 시간표 로직 리팩토링
  src/main/java/com/asap/server/presentation/controller/dto/request/AvailableTimeRequestDto.java
  src/main/java/com/asap/server/presentation/controller/dto/request/UserMeetingTimeSaveRequestDto.java
  src/main/java/com/asap/server/presentation/controller/dto/response/AvailableDatesDto.java
  src/main/java/com/asap/server/presentation/controller/dto/response/TimeSlotDto.java
  src/main/java/com/asap/server/presentation/controller/dto/response/TimeTableResponseDto.java
  src/main/java/com/asap/server/presentation/controller/meeting/MeetingRetrieveController.java
  src/main/java/com/asap/server/service/TimeBlockUserService.java
  src/main/java/com/asap/server/service/UserService.java
  src/main/java/com/asap/server/service/meeting/MeetingRetrieveService.java
  src/main/java/com/asap/server/service/time/UserMeetingScheduleService.java
  src/main/java/com/asap/server/service/time/dto/register/UserMeetingScheduleRegisterDto.java
  src/main/java/com/asap/server/service/time/dto/register/UserTimeRegisterDto.java
  src/main/java/com/asap/server/service/time/dto/retrieve/AvailableDatesRetrieveDto.java
  src/main/java/com/asap/server/service/time/dto/retrieve/TimeBlockRetrieveDto.java
  src/main/java/com/asap/server/service/time/dto/retrieve/TimeTableRetrieveDto.java
  src/main/java/com/asap/server/service/user/UserRetrieveService.java
  src/test/java/com/asap/server/service/meeting/MeetingRetrieveServiceTest.java
Labels: Highest

#329 #328 [fix] slack util deprecated api 수정
  build.gradle
  src/main/java/com/asap/server/infra/slack/SlackUtil.java
  src/main/java/com/asap/server/persistence/domain/time/UserMeetingSchedule.java
Labels: Medium
